In [1]:
!pip3 install numpy

In [2]:
import numpy as np

In [3]:
np.__version__

'1.19.2'

In [4]:
array1 = np.array(range(30))

In [5]:
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [9]:
a = array1.reshape(5,6)
a.ravel(order="F")

array([ 0,  6, 12, 18, 24,  1,  7, 13, 19, 25,  2,  8, 14, 20, 26,  3,  9,
       15, 21, 27,  4, 10, 16, 22, 28,  5, 11, 17, 23, 29])

In [12]:
np.where(a%6==1)

(array([0, 1, 2, 3, 4], dtype=int64), array([1, 1, 1, 1, 1], dtype=int64))